In [3]:
# Use this to upload your dataset, it is just once.
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv

In [4]:
import pandas as pd

###### # Re-loading the dataset using ';' or ';' as the delimiter
data = pd.read_csv("data.csv", delimiter=';')

In [5]:
# Displaying the first few rows of the dataset
data.describe()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,...,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,1.178571,18.669078,1.727848,8856.642631,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
std,0.605747,17.484682,1.313793,2063.566416,0.311897,10.216592,13.188332,6.914514,15.603186,15.343108,...,0.690880,1.918546,2.195951,3.947951,3.014764,5.210808,0.753774,2.663850,1.382711,2.269935
min,1.000000,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,1.000000,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,1.000000,19.000000,19.000000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,1.000000,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,1.000000,37.000000,37.000000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,6.000000,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,109.000000,44.000000,44.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000

In [7]:
# Filtramos el DataFrame para excluir las filas con "Enrolled" en la columna "Target"
data_test = data[data['Target'] != 'Enrolled']
data = data[data['Target'] != 'Enrolled']
len(data)

3630

In [8]:
# Checking for missing values in the dataset
missing_values = data.isnull().sum()

# Displaying columns with missing values (if any)
missing_values[missing_values > 0]

Series([], dtype: int64)

In [10]:
from sklearn.preprocessing import StandardScaler

# Encoding categorical variables using one-hot encoding
data_encoded = pd.get_dummies(data, drop_first=True)

# Extracting features and target variables
X = data_encoded.drop(columns=['Target_Desertor','Target_Graduate'], errors='ignore')
y = data['Target'].map({'Dropout': 1, 'Graduate': 0})

# Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Displaying the first few rows of the encoded dataset
data_encoded.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target_Graduate
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,0
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,1
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,0
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,1
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,1

In [11]:
# We do this to save these columns and use it in flask app
import joblib

# Guardar las columnas del dataframe codificado en una lista
training_columns = X.columns.tolist()

# Guardar la lista en un archivo .pkl
joblib.dump(training_columns, 'training_columns.pkl')
print(training_columns)

['Marital status', 'Application mode', 'Application order', 'Course', 'Daytime/evening attendance\t', 'Previous qualification', 'Previous qualification (grade)', 'Nacionality', "Mother's qualification", "Father's qualification", "Mother's occupation", "Father's occupation", 'Admission grade', 'Displaced', 'Educational special needs', 'Debtor', 'Tuition fees up to date', 'Gender', 'Scholarship holder', 'Age at enrollment', 'International', 'Curricular units 1st sem (credited)', 'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 'Curricular units 2nd sem (without evaluations)', 'Unemployment rate', 'Inflation rate', 'GDP']

#Training the model

In [13]:
from sklearn.model_selection import train_test_split

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape

((2904, 36), (726, 36))

In [14]:
# Checking for NaN values in the target variable 'y'
nan_rows = y[y.isnull()]

nan_rows

Series([], Name: Target, dtype: int64)

In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

# Training the logistic regression model on cleaned data
logistic_model = LogisticRegression(max_iter=10000)
logistic_model.fit(X_train, y_train)

# Predicting on the cleaned test set
y_pred = logistic_model.predict(X_test)

# Calculating accuracy for cleaned data
accuracy = accuracy_score(y_test, y_pred)

# Displaying classification report and accuracy for cleaned data
classification_rep= classification_report(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Accuracy: ",accuracy)
print(classification_rep)
print("Confusion Matrix: \n",confusion_mat)

Accuracy:  0.9104683195592287
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       449
           1       0.92      0.84      0.88       277

    accuracy                           0.91       726
   macro avg       0.91      0.90      0.90       726
weighted avg       0.91      0.91      0.91       726

Confusion Matrix:
 [[428  21]
 [ 44 233]]

In [22]:
import joblib

# Save the model
joblib.dump(logistic_model, 'logistic_model.pkl')

# Save the scaler
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

# Make predictions

In [23]:
import joblib

# Carga el modelo y el escaler
model = joblib.load('logistic_model.pkl')
scaler = joblib.load('scaler.pkl')

In [33]:
# 1. Select some rows as an example (here I am selecting the first 30)
sample_data = data_test.iloc[:30].drop(columns=['Target'])  # assuming that 'Target' is your output column

# 2. Preprocessing
# Performs the one-hot encoding
sample_encoded = pd.get_dummies(sample_data)
sample_encoded = sample_encoded.drop(columns=['Target_Desertor','Target_Graduate'], errors='ignore')
# Make sure that all expected columns are present in the test dataset
for col in training_columns:
    if col not in sample_encoded.columns:
        sample_encoded[col] = 0

# Reorder the columns
sample_encoded = sample_encoded[training_columns]

# Escale features
sample_scaled = scaler.transform(sample_encoded)

# 3. Prediction
predictions = model.predict(sample_scaled)

# 4. Evaluate
print("Predicciones:", predictions)
print("Valores reales:\n", data_test['Target'].iloc[:30].values)

Predicciones: [1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
Valores reales:
 ['Dropout' 'Graduate' 'Dropout' 'Graduate' 'Graduate' 'Graduate'
 'Graduate' 'Dropout' 'Graduate' 'Dropout' 'Graduate' 'Graduate' 'Dropout'
 'Graduate' 'Graduate' 'Dropout' 'Graduate' 'Graduate' 'Graduate'
 'Graduate' 'Graduate' 'Graduate' 'Graduate' 'Graduate' 'Graduate'
 'Graduate' 'Graduate' 'Dropout' 'Dropout' 'Dropout']